In [1]:
import numpy as np
from skimage import io
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

In [11]:
plt.rcParams['figure.figsize'] = (20, 12)
image = io.imread('pl.jpg')
labels = plt.axes(xticks=[], yticks=[])
labels.imshow(image);

Output hidden; open in https://colab.research.google.com to view.

In [12]:
rows = image.shape[0]
cols = image.shape[1]
image = image.reshape(rows*cols, 3)

In [13]:
kmeans = KMeans(n_clusters=10)
kmeans.fit(image)

KMeans(n_clusters=10)

In [14]:
print(image)

[[ 35  84 150]
 [ 25  79 143]
 [ 27  78 141]
 ...
 [136 135 141]
 [130 129 135]
 [132 131 136]]


In [15]:
compressed_image = kmeans.cluster_centers_[kmeans.labels_]
compressed_image = np.clip(compressed_image.astype('uint8'), 0, 255)

In [ ]:
compressed_image = compressed_image.reshape(rows, cols, 3)
io.imsave('compressed_image_64.png', compressed_image)
io.imshow(compressed_image)
io.show()